{
  "hash": "e893a3769bfcb59ff08326bd68ef5544",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Olivetti Faces PCA Migration\"\nformat: html\nexecute:\n  echo: true\n  warning: false\n---\n\n## Overview\n\nThis note documents the migration from the original Julia PCA workflow to Python for the Olivetti faces dataset.\n\nThe original project used a train/test split, a PCA projection, and a reconstruction step. The Python implementation keeps the same structure while working with `numpy` and `scikit-learn`.\n\n## Data loading\n\n::: {#load-data .cell execution_count=1}\n``` {.python .cell-code}\nimport sys\nfrom pathlib import Path\n\nroot = Path.cwd().resolve()\nfor candidate in [root, *([root.parent] if root.name != \"olivetti-faces-project\" else [])]:\n    if (candidate / \"olivetti_faces\").exists():\n        project_root = candidate\n        break\nelse:\n    project_root = root\n\nvenv_site = project_root / \".venv\" / \"lib\" / f\"python{sys.version_info.major}.{sys.version_info.minor}\" / \"site-packages\"\nif venv_site.exists():\n    sys.path.insert(0, str(project_root))\n    sys.path.insert(0, str(venv_site))\n\nfrom olivetti_faces.data import load_olivetti_faces\n\n(X_train, X_test), (y_train, y_test) = load_olivetti_faces(test_size=0.2, random_state=123)\nprint(X_train.shape)\nprint(X_test.shape)\nprint(y_train.shape)\nprint(y_test.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(320, 4096)\n(80, 4096)\n(320,)\n(80,)\n```\n:::\n:::\n\n\n## PCA fitting\n\n::: {#fit-pca .cell execution_count=2}\n``` {.python .cell-code}\nfrom olivetti_faces.model import make_model\n\nmodel = make_model(X_train, n_components=10)\nprint(model[\"pca\"].n_components)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n10\n```\n:::\n:::\n\n\n## Projection and reconstruction\n\n::: {#project-reconstruct .cell execution_count=3}\n``` {.python .cell-code}\nfrom olivetti_faces.model import transform_to_pcadata, reconstruct_data\n\nprojected = transform_to_pcadata(model, X_train[:5])\nreconstructed = reconstruct_data(model, projected)\nprint(projected.shape)\nprint(reconstructed.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(5, 10)\n(5, 4096)\n```\n:::\n:::\n\n\n## Reconstruction quality\n\nThe project includes a direct comparison between the original face and the reconstructed versions using different PCA component counts.\n\n![](../imgs/reconstructed_face.png)\n\nThis makes it clear that higher-dimensional PCA models recover more detail while lower-dimensional models produce a smoother approximation.\n\n## Model accuracy comparison\n\nWe can compare reconstruction error as the number of retained components changes.\n\n![](../imgs/model_accuracy_comparison.png)\n\nThe expected pattern is that reconstruction error decreases as the model dimension increases, with a clear tradeoff between compact representation and accuracy.\n\n## Expected behavior\n\n- The training matrix has shape `(320, 4096)` for the 80/20 split.\n- PCA projection from 4096 features to 10 dimensions should keep the same reconstruction workflow.\n- Reconstructed faces should approximate the originals with small reconstruction error.\n- More PCA components should reduce reconstruction error and preserve more facial detail.\n\n## Notes\n\nThis migration intentionally excludes the generated model artifacts and the removed legacy Stat2 folder from the repository branch.\n\n",
    "supporting": [
      "olivetti-pca_files"
    ],
    "filters": [],
    "includes": {}
  }
}